"""add fair note

Revision ID: 006d555b3fd2
Revises: 065bbbcf1688
Create Date: 2025-10-09 09:55:06.099734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006d555b3fd2'
down_revision: Union[str, Sequence[str], None] = '065bbbcf1688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_lots', sa.Column('fair_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'fair_note')
    # ### end Alembic commands ###
