"""add is_paid to break_entries

Revision ID: 00dc7b28f10e
Revises: 896eda5db2c5
Create Date: 2025-08-19 22:06:09.774091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dc7b28f10e'
down_revision: Union[str, Sequence[str], None] = '896eda5db2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_time_entries_one_open'), table_name='time_entries', postgresql_where="((status)::text = 'open'::text)")
    op.drop_constraint(op.f('users_employee_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.drop_constraint(op.f('users_employee_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.add_column(
        'break_entries',
        sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ถ้าอยากเอา default ออกหลังเติมค่าให้ row เก่าแล้ว:
    op.alter_column('break_entries', 'is_paid', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_employee_id_fkey'), 'users', 'employees', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.create_unique_constraint(op.f('users_employee_id_key'), 'users', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_time_entries_one_open'), 'time_entries', ['employee_id'], unique=True, postgresql_where="((status)::text = 'open'::text)")
    op.drop_column('break_entries', 'is_paid')
    # ### end Alembic commands ###
