"""add remove UOM

Revision ID: 053a795072dc
Revises: f515b06b2cc4
Create Date: 2026-01-07 11:56:27.491533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053a795072dc'
down_revision: Union[str, Sequence[str], None] = 'f515b06b2cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traveler_template_steps', 'default_uom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler_template_steps', sa.Column('default_uom', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
