"""add users and time_entries tables

Revision ID: 0ddac742f06b
Revises: f3a3cc70ca43
Create Date: 2026-06-18 15:13:43.176378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddac742f06b'
down_revision: Union[str, Sequence[str], None] = 'f3a3cc70ca43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('prod_qty', sa.Integer(), nullable=True),
    sa.Column('ship_qty', sa.Integer(), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_table('lot_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_lot_id', sa.Integer(), nullable=False),
    sa.Column('to_lot_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['to_lot_id'], ['production_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_transfers_from_lot_id'), 'lot_transfers', ['from_lot_id'], unique=False)
    op.create_index(op.f('ix_lot_transfers_to_lot_id'), 'lot_transfers', ['to_lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_transfers_to_lot_id'), table_name='lot_transfers')
    op.drop_index(op.f('ix_lot_transfers_from_lot_id'), table_name='lot_transfers')
    op.drop_table('lot_transfers')
    op.drop_table('inventory')
    # ### end Alembic commands ###
