"""add mat po no

Revision ID: 0e52a98addf0
Revises: d04b30c1feb9
Create Date: 2025-10-15 16:33:48.847085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e52a98addf0'
down_revision: Union[str, Sequence[str], None] = 'd04b30c1feb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_pos', sa.Column('mat_po_no', sa.String(), nullable=True))
    op.alter_column('material_pos', 'po_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_material_pos_mat_po_no'), 'material_pos', ['mat_po_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_pos_mat_po_no'), table_name='material_pos')
    op.alter_column('material_pos', 'po_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('material_pos', 'mat_po_no')
    # ### end Alembic commands ###
