"""add op_no

Revision ID: 12ae6ee30a1f
Revises: aeed57f10f51
Create Date: 2026-01-11 14:25:27.503812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ae6ee30a1f'
down_revision: Union[str, Sequence[str], None] = 'aeed57f10f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_inspection_template_items', sa.Column('op_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_inspection_template_items', 'op_no')
    # ### end Alembic commands ###
