"""update tables

Revision ID: 1bfe6b85e643
Revises: 9e50f2df3f09
Create Date: 2026-05-13 09:50:37.893584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe6b85e643'
down_revision: Union[str, Sequence[str], None] = '9e50f2df3f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('input_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_traveler_steps', 'input_mode')
    # ### end Alembic commands ###
