"""add pay_rates table

Revision ID: 1d415228c202
Revises: 5766fea2bc25
Create Date: 2025-08-27 09:10:18.950208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d415228c202'
down_revision: Union[str, Sequence[str], None] = '5766fea2bc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ot_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('dt_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pay_rates_emp_eff', 'pay_rates', ['employee_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_pay_rates_employee_id'), 'pay_rates', ['employee_id'], unique=False)
    op.add_column('time_entries', sa.Column('work_user_id', sa.Integer(), nullable=True))
    op.create_index('ix_time_entries_emp_work_week', 'time_entries', ['employee_id', 'work_user_id', 'clock_in_at'], unique=False)
    op.create_index('ix_time_entries_work_user', 'time_entries', ['work_user_id'], unique=False)
    op.create_index(op.f('ix_time_entries_work_user_id'), 'time_entries', ['work_user_id'], unique=False)
    op.create_foreign_key(None, 'time_entries', 'users', ['work_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_index(op.f('ix_time_entries_work_user_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_work_user', table_name='time_entries')
    op.drop_index('ix_time_entries_emp_work_week', table_name='time_entries')
    op.drop_column('time_entries', 'work_user_id')
    op.drop_index(op.f('ix_pay_rates_employee_id'), table_name='pay_rates')
    op.drop_index('ix_pay_rates_emp_eff', table_name='pay_rates')
    op.drop_table('pay_rates')
    # ### end Alembic commands ###
