"""init tables

Revision ID: 1ddb9fc8858c
Revises: fa4e65b8f2e7
Create Date: 2025-08-10 21:10:57.676132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddb9fc8858c'
down_revision: Union[str, Sequence[str], None] = 'fa4e65b8f2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('raw_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_materials_code'), 'raw_materials', ['code'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('raw_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(), nullable=False),
    sa.Column('supplier_batch_no', sa.String(), nullable=True),
    sa.Column('mill_name', sa.String(), nullable=True),
    sa.Column('mill_heat_no', sa.String(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_used', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('cert_file', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'batch_no', 'supplier_id', name='uq_batch_material_supplier')
    )
    op.create_index(op.f('ix_raw_batches_batch_no'), 'raw_batches', ['batch_no'], unique=False)
    op.create_index('ix_raw_batches_mat_recv', 'raw_batches', ['material_id', 'received_at'], unique=False)
    op.create_table('subcon_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subcon_orders_supplier_status', 'subcon_orders', ['supplier_id', 'status'], unique=False)
    op.create_table('production_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(), nullable=False),
    sa.Column('part_no', sa.String(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lots_lot_no'), 'production_lots', ['lot_no'], unique=True)
    op.create_table('subcon_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('doc_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['subcon_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcon_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.Column('shipped_by', sa.String(), nullable=True),
    sa.Column('package_no', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('tracking_no', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['subcon_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_material_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['raw_batches.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lmu_batch', 'lot_material_use', ['batch_id'], unique=False)
    op.create_index('ix_lmu_lot', 'lot_material_use', ['lot_id'], unique=False)
    op.create_table('shop_travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_index('ix_shop_travelers_status', 'shop_travelers', ['status'], unique=False)
    op.create_table('shop_traveler_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('station', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('qa_required', sa.Boolean(), nullable=False),
    sa.Column('qa_result', sa.String(), nullable=True),
    sa.Column('qa_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['shop_travelers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traveler_id', 'seq', name='uq_traveler_seq')
    )
    op.create_index('ix_traveler_steps_operator', 'shop_traveler_steps', ['operator_id'], unique=False)
    op.create_index('ix_traveler_steps_status', 'shop_traveler_steps', ['status'], unique=False)
    op.create_table('subcon_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('traveler_step_id', sa.Integer(), nullable=False),
    sa.Column('qty_planned', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['subcon_orders.id'], ),
    sa.ForeignKeyConstraint(['traveler_step_id'], ['shop_traveler_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'traveler_step_id', name='uq_order_step')
    )
    op.create_index('ix_subcon_order_lines_step', 'subcon_order_lines', ['traveler_step_id'], unique=False)
    op.create_table('subcon_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('traveler_step_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_rejected', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('scrap_qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qa_result', sa.String(), nullable=True),
    sa.Column('qa_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['subcon_receipts.id'], ),
    sa.ForeignKeyConstraint(['traveler_step_id'], ['shop_traveler_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subcon_receipt_items_step', 'subcon_receipt_items', ['traveler_step_id'], unique=False)
    op.create_table('subcon_shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('traveler_step_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['subcon_shipments.id'], ),
    sa.ForeignKeyConstraint(['traveler_step_id'], ['shop_traveler_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subcon_shipment_items_step', 'subcon_shipment_items', ['traveler_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subcon_shipment_items_step', table_name='subcon_shipment_items')
    op.drop_table('subcon_shipment_items')
    op.drop_index('ix_subcon_receipt_items_step', table_name='subcon_receipt_items')
    op.drop_table('subcon_receipt_items')
    op.drop_index('ix_subcon_order_lines_step', table_name='subcon_order_lines')
    op.drop_table('subcon_order_lines')
    op.drop_index('ix_traveler_steps_status', table_name='shop_traveler_steps')
    op.drop_index('ix_traveler_steps_operator', table_name='shop_traveler_steps')
    op.drop_table('shop_traveler_steps')
    op.drop_index('ix_shop_travelers_status', table_name='shop_travelers')
    op.drop_table('shop_travelers')
    op.drop_index('ix_lmu_lot', table_name='lot_material_use')
    op.drop_index('ix_lmu_batch', table_name='lot_material_use')
    op.drop_table('lot_material_use')
    op.drop_table('subcon_shipments')
    op.drop_table('subcon_receipts')
    op.drop_index(op.f('ix_production_lots_lot_no'), table_name='production_lots')
    op.drop_table('production_lots')
    op.drop_index('ix_subcon_orders_supplier_status', table_name='subcon_orders')
    op.drop_table('subcon_orders')
    op.drop_index('ix_raw_batches_mat_recv', table_name='raw_batches')
    op.drop_index(op.f('ix_raw_batches_batch_no'), table_name='raw_batches')
    op.drop_table('raw_batches')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_raw_materials_code'), table_name='raw_materials')
    op.drop_table('raw_materials')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
