"""edit time entries

Revision ID: 200f8f129324
Revises: aed3e6e0b960
Create Date: 2025-09-05 22:17:40.110098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200f8f129324'
down_revision: Union[str, Sequence[str], None] = 'aed3e6e0b960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_periods', sa.Column('created_by_emp_id', sa.Integer(), nullable=True))
    op.add_column('pay_periods', sa.Column('locked_by_emp_id', sa.Integer(), nullable=True))
    op.add_column('pay_periods', sa.Column('paid_by_emp_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pay_periods', 'employees', ['created_by_emp_id'], ['id'])
    op.create_foreign_key(None, 'pay_periods', 'employees', ['paid_by_emp_id'], ['id'])
    op.create_foreign_key(None, 'pay_periods', 'employees', ['locked_by_emp_id'], ['id'])
    op.add_column('time_entries', sa.Column('pay_period_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_time_entries_pay_period_id'), 'time_entries', ['pay_period_id'], unique=False)
    op.create_foreign_key(None, 'time_entries', 'pay_periods', ['pay_period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_index(op.f('ix_time_entries_pay_period_id'), table_name='time_entries')
    op.drop_column('time_entries', 'pay_period_id')
    op.drop_constraint(None, 'pay_periods', type_='foreignkey')
    op.drop_constraint(None, 'pay_periods', type_='foreignkey')
    op.drop_constraint(None, 'pay_periods', type_='foreignkey')
    op.drop_column('pay_periods', 'paid_by_emp_id')
    op.drop_column('pay_periods', 'locked_by_emp_id')
    op.drop_column('pay_periods', 'created_by_emp_id')
    # ### end Alembic commands ###
