"""update tables st and inspection

Revision ID: 208c48176714
Revises: 8ab0894e78da
Create Date: 2026-08-13 09:31:52.749868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208c48176714'
down_revision: Union[str, Sequence[str], None] = '8ab0894e78da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_inspections', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qa_inspections', sa.Column('edited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qa_inspections', 'employees', ['edited_by_id'], ['id'])
    op.add_column('shop_travelers', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shop_travelers', sa.Column('edited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shop_travelers', 'employees', ['edited_by_id'], ['id'])
    op.add_column('traveler_templates', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('traveler_templates', sa.Column('edited_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'traveler_templates', 'employees', ['edited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traveler_templates', type_='foreignkey')
    op.drop_column('traveler_templates', 'edited_by_id')
    op.drop_column('traveler_templates', 'edited_at')
    op.drop_constraint(None, 'shop_travelers', type_='foreignkey')
    op.drop_column('shop_travelers', 'edited_by_id')
    op.drop_column('shop_travelers', 'edited_at')
    op.drop_constraint(None, 'qa_inspections', type_='foreignkey')
    op.drop_column('qa_inspections', 'edited_by_id')
    op.drop_column('qa_inspections', 'edited_at')
    # ### end Alembic commands ###
