"""add lot_due_date to production_lot

Revision ID: 225617dee147
Revises: 849107fd04c8
Create Date: 2025-09-24 16:15:37.336788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225617dee147'
down_revision: Union[str, Sequence[str], None] = '849107fd04c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('lot_due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_production_lots_lot_due_date'), 'production_lots', ['lot_due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_lots_lot_due_date'), table_name='production_lots')
    op.drop_column('production_lots', 'lot_due_date')
    # ### end Alembic commands ###
