"""add RawBatchReference

Revision ID: 22b3c00d9d3a
Revises: 5a45fed6d284
Create Date: 2026-07-02 11:42:12.884878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b3c00d9d3a'
down_revision: Union[str, Sequence[str], None] = '5a45fed6d284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_batches', 'printed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_batches', 'printed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
