"""add package_no to customer_shipments

Revision ID: 23b883c5e05b
Revises: cdad821dd4b3
Create Date: 2025-10-09 08:12:43.541019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b883c5e05b'
down_revision: Union[str, Sequence[str], None] = 'cdad821dd4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_mat_category_catalog',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['supplier_mat_category_catalog.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('supplier_service_catalog',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('supplier_material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('price_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['supplier_mat_category_catalog.code'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'category_code', name='uq_supplier_matcat_once')
    )
    op.create_index('ix_supplier_matcat_lookup', 'supplier_material_categories', ['category_code', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_material_categories_category_code'), 'supplier_material_categories', ['category_code'], unique=False)
    op.create_index(op.f('ix_supplier_material_categories_supplier_id'), 'supplier_material_categories', ['supplier_id'], unique=False)
    op.create_table('supplier_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_code'], ['supplier_service_catalog.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'service_code', name='uq_supplier_service_once')
    )
    op.create_index('ix_supplier_services_lookup', 'supplier_services', ['service_code', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_services_service_code'), 'supplier_services', ['service_code'], unique=False)
    op.create_index(op.f('ix_supplier_services_supplier_id'), 'supplier_services', ['supplier_id'], unique=False)
    op.add_column('customer_shipments', sa.Column('package_no', sa.String(), nullable=True))
    op.create_index(op.f('ix_customer_shipments_package_no'), 'customer_shipments', ['package_no'], unique=False)
    op.add_column('production_lots', sa.Column('note', sa.String(), nullable=True))
    op.create_index(op.f('ix_raw_materials_family_code'), 'raw_materials', ['family_code'], unique=False)
    op.create_index(op.f('ix_raw_materials_form_code'), 'raw_materials', ['form_code'], unique=False)
    op.create_index(op.f('ix_raw_materials_grade_code'), 'raw_materials', ['grade_code'], unique=False)
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['family_code'], ['code'])
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['form_code'], ['code'])
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['grade_code'], ['code'])
    op.add_column('shop_traveler_steps', sa.Column('step_note', sa.Text(), nullable=True))
    op.alter_column('suppliers', 'is_material_supplier',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('suppliers', 'is_subcontractor',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_suppliers_roles', 'suppliers', ['is_material_supplier', 'is_subcontractor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suppliers_roles', table_name='suppliers')
    op.alter_column('suppliers', 'is_subcontractor',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('suppliers', 'is_material_supplier',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('shop_traveler_steps', 'step_note')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_index(op.f('ix_raw_materials_grade_code'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_form_code'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_family_code'), table_name='raw_materials')
    op.drop_column('production_lots', 'note')
    op.drop_index(op.f('ix_customer_shipments_package_no'), table_name='customer_shipments')
    op.drop_column('customer_shipments', 'package_no')
    op.drop_index(op.f('ix_supplier_services_supplier_id'), table_name='supplier_services')
    op.drop_index(op.f('ix_supplier_services_service_code'), table_name='supplier_services')
    op.drop_index('ix_supplier_services_lookup', table_name='supplier_services')
    op.drop_table('supplier_services')
    op.drop_index(op.f('ix_supplier_material_categories_supplier_id'), table_name='supplier_material_categories')
    op.drop_index(op.f('ix_supplier_material_categories_category_code'), table_name='supplier_material_categories')
    op.drop_index('ix_supplier_matcat_lookup', table_name='supplier_material_categories')
    op.drop_table('supplier_material_categories')
    op.drop_table('supplier_service_catalog')
    op.drop_table('supplier_mat_category_catalog')
    # ### end Alembic commands ###
