"""add auto  time

Revision ID: 24dbdb41ca89
Revises: 4d30f3029f0c
Create Date: 2025-08-19 22:23:24.297150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24dbdb41ca89'
down_revision: Union[str, Sequence[str], None] = '4d30f3029f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_entries', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_entries', 'is_paid')
    # ### end Alembic commands ###
