"""update lot tables

Revision ID: 27dcf0d9dea6
Revises: 4131367ffb44
Create Date: 2025-12-27 23:45:07.542978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27dcf0d9dea6'
down_revision: Union[str, Sequence[str], None] = '4131367ffb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_lots', 'lot_po_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('production_lots', 'lot_due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('production_lots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_production_lots_lot_due_date'), table_name='production_lots')
    op.drop_index(op.f('ix_production_lots_lot_po_date'), table_name='production_lots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_production_lots_lot_po_date'), 'production_lots', ['lot_po_date'], unique=False)
    op.create_index(op.f('ix_production_lots_lot_due_date'), 'production_lots', ['lot_due_date'], unique=False)
    op.alter_column('production_lots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('production_lots', 'lot_due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('production_lots', 'lot_po_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
