"""update tables

Revision ID: 280a4ba12e51
Revises: 1bfe6b85e643
Create Date: 2026-05-15 15:05:04.686077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a4ba12e51'
down_revision: Union[str, Sequence[str], None] = '1bfe6b85e643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gage_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('gage_range', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('calibration_frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('gage_owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gages_gage_id'), 'gages', ['gage_id'], unique=True)
    op.create_index(op.f('ix_gages_next_due_date'), 'gages', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_gages_serial_number'), 'gages', ['serial_number'], unique=False)
    op.create_table('gage_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gage_id', sa.Integer(), nullable=False),
    sa.Column('date_calibrated', sa.Date(), nullable=False),
    sa.Column('calibrated_by', sa.String(), nullable=True),
    sa.Column('calibration_vendor', sa.String(), nullable=True),
    sa.Column('standard_used', sa.String(), nullable=True),
    sa.Column('calibration_cert_no', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gage_id'], ['gages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gage_calibrations_gage_id'), 'gage_calibrations', ['gage_id'], unique=False)
    op.create_table('icars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icar_no', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('part_revision_id', sa.Integer(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('traveler_step_id', sa.Integer(), nullable=True),
    sa.Column('qa_inspection_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('approve_id', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('po_no', sa.String(), nullable=True),
    sa.Column('lot_no', sa.String(), nullable=True),
    sa.Column('part_no', sa.String(), nullable=True),
    sa.Column('rev', sa.String(), nullable=True),
    sa.Column('part_name', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('lot_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('defect_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('defect_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('non_conformity', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('immediate_corrective_action', sa.Text(), nullable=True),
    sa.Column('systemic_corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approve_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['qa_inspection_id'], ['qa_inspections.id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['shop_travelers.id'], ),
    sa.ForeignKeyConstraint(['traveler_step_id'], ['shop_traveler_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icar_no')
    )
    op.create_index(op.f('ix_icars_customer_id'), 'icars', ['customer_id'], unique=False)
    op.create_index(op.f('ix_icars_lot_id'), 'icars', ['lot_id'], unique=False)
    op.create_index(op.f('ix_icars_part_id'), 'icars', ['part_id'], unique=False)
    op.create_index(op.f('ix_icars_part_revision_id'), 'icars', ['part_revision_id'], unique=False)
    op.create_index(op.f('ix_icars_po_id'), 'icars', ['po_id'], unique=False)
    op.create_table('ecars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecar_no', sa.String(), nullable=False),
    sa.Column('date_initiated', sa.Date(), nullable=True),
    sa.Column('close_out_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('part_revision_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.String(), nullable=True),
    sa.Column('ncr_rma_job_no', sa.String(), nullable=True),
    sa.Column('po_no', sa.String(), nullable=True),
    sa.Column('part_no', sa.String(), nullable=True),
    sa.Column('part_description', sa.String(), nullable=True),
    sa.Column('rev', sa.String(), nullable=True),
    sa.Column('reject_tag_idr', sa.String(), nullable=True),
    sa.Column('car_no', sa.String(), nullable=True),
    sa.Column('shipped_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('rtv_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('customer_rework_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('use_as_is_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('defect_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('scar_issue', sa.Text(), nullable=True),
    sa.Column('scar_reply', sa.Text(), nullable=True),
    sa.Column('discrepancy', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['customer_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecars_customer_id'), 'ecars', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ecars_date_initiated'), 'ecars', ['date_initiated'], unique=False)
    op.create_index(op.f('ix_ecars_ecar_no'), 'ecars', ['ecar_no'], unique=True)
    op.create_index(op.f('ix_ecars_lot_id'), 'ecars', ['lot_id'], unique=False)
    op.create_index(op.f('ix_ecars_part_id'), 'ecars', ['part_id'], unique=False)
    op.create_index(op.f('ix_ecars_part_revision_id'), 'ecars', ['part_revision_id'], unique=False)
    op.create_index(op.f('ix_ecars_po_id'), 'ecars', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ecars_po_id'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_part_revision_id'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_part_id'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_lot_id'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_ecar_no'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_date_initiated'), table_name='ecars')
    op.drop_index(op.f('ix_ecars_customer_id'), table_name='ecars')
    op.drop_table('ecars')
    op.drop_index(op.f('ix_icars_po_id'), table_name='icars')
    op.drop_index(op.f('ix_icars_part_revision_id'), table_name='icars')
    op.drop_index(op.f('ix_icars_part_id'), table_name='icars')
    op.drop_index(op.f('ix_icars_lot_id'), table_name='icars')
    op.drop_index(op.f('ix_icars_customer_id'), table_name='icars')
    op.drop_table('icars')
    op.drop_index(op.f('ix_gage_calibrations_gage_id'), table_name='gage_calibrations')
    op.drop_table('gage_calibrations')
    op.drop_index(op.f('ix_gages_serial_number'), table_name='gages')
    op.drop_index(op.f('ix_gages_next_due_date'), table_name='gages')
    op.drop_index(op.f('ix_gages_gage_id'), table_name='gages')
    op.drop_table('gages')
    # ### end Alembic commands ###
