"""edit revision

Revision ID: 2ec17fcab11b
Revises: 200f8f129324
Create Date: 2025-09-05 22:32:13.844700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec17fcab11b'
down_revision: Union[str, Sequence[str], None] = '200f8f129324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_part_id_id', 'part_revisions', ['part_id', 'id'])
    op.create_index(op.f('ix_po_lines_part_id'), 'po_lines', ['part_id'], unique=False)
    op.create_index('ix_po_lines_part_rev', 'po_lines', ['part_id', 'revision_id'], unique=False)
    op.create_index(op.f('ix_po_lines_revision_id'), 'po_lines', ['revision_id'], unique=False)
    op.drop_constraint(op.f('po_lines_revision_id_fkey'), 'po_lines', type_='foreignkey')
    op.create_foreign_key('fk_poline_part_rev_pair', 'po_lines', 'part_revisions', ['part_id', 'revision_id'], ['part_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_poline_part_rev_pair', 'po_lines', type_='foreignkey')
    op.create_foreign_key(op.f('po_lines_revision_id_fkey'), 'po_lines', 'part_revisions', ['revision_id'], ['id'])
    op.drop_index(op.f('ix_po_lines_revision_id'), table_name='po_lines')
    op.drop_index('ix_po_lines_part_rev', table_name='po_lines')
    op.drop_index(op.f('ix_po_lines_part_id'), table_name='po_lines')
    op.drop_constraint('uq_part_id_id', 'part_revisions', type_='unique')
    # ### end Alembic commands ###
