"""update tables

Revision ID: 31ae8d73d355
Revises: d131c9523501
Create Date: 2026-04-28 10:27:11.387986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ae8d73d355'
down_revision: Union[str, Sequence[str], None] = 'd131c9523501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_traveler_step_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qty_receive', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('qty_accept', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_reject', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('qty_rework', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('qty_accept >= 0', name='ck_accept_positive'),
    sa.CheckConstraint('qty_reject >= 0', name='ck_reject_positive'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['shop_traveler_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'work_date', name='uq_step_day')
    )
    op.create_index(op.f('ix_shop_traveler_step_logs_step_id'), 'shop_traveler_step_logs', ['step_id'], unique=False)
    op.create_index(op.f('ix_shop_traveler_step_logs_work_date'), 'shop_traveler_step_logs', ['work_date'], unique=False)
    op.create_index('ix_step_log_machine', 'shop_traveler_step_logs', ['machine_id'], unique=False)
    op.create_index('ix_step_log_operator', 'shop_traveler_step_logs', ['operator_id'], unique=False)
    op.drop_column('shop_traveler_steps', 'qty_rework')
    op.drop_column('shop_traveler_steps', 'qty_accept')
    op.drop_column('shop_traveler_steps', 'qty_reject')
    op.drop_column('shop_traveler_steps', 'qty_receive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('qty_receive', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False))
    op.add_column('shop_traveler_steps', sa.Column('qty_reject', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False))
    op.add_column('shop_traveler_steps', sa.Column('qty_accept', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=False))
    op.add_column('shop_traveler_steps', sa.Column('qty_rework', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=True))
    op.drop_index('ix_step_log_operator', table_name='shop_traveler_step_logs')
    op.drop_index('ix_step_log_machine', table_name='shop_traveler_step_logs')
    op.drop_index(op.f('ix_shop_traveler_step_logs_work_date'), table_name='shop_traveler_step_logs')
    op.drop_index(op.f('ix_shop_traveler_step_logs_step_id'), table_name='shop_traveler_step_logs')
    op.drop_table('shop_traveler_step_logs')
    # ### end Alembic commands ###
