"""update tables

Revision ID: 31b3af0616b6
Revises: e5c19ce54ce2
Create Date: 2026-05-05 23:11:18.463818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b3af0616b6'
down_revision: Union[str, Sequence[str], None] = 'e5c19ce54ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_qa_inspection_templates_active'), 'qa_inspection_templates', ['active'], unique=False)
    op.add_column('shop_travelers', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shop_travelers', 'traveler_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_travelers', type_='foreignkey')
    op.drop_column('shop_travelers', 'template_id')
    op.drop_index(op.f('ix_qa_inspection_templates_active'), table_name='qa_inspection_templates')
    # ### end Alembic commands ###
