"""updatet create at po 

Revision ID: 32a7dcac0cd2
Revises: 3ffacf681db0
Create Date: 2025-10-03 14:32:27.656470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a7dcac0cd2'
down_revision: Union[str, Sequence[str], None] = '3ffacf681db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_lines', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'created_at')
    op.drop_column('po_lines', 'created_at')
    # ### end Alembic commands ###
