"""add meterail line

Revision ID: 32f8888df442
Revises: 394e71379ae4
Create Date: 2025-09-05 14:11:09.441459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f8888df442'
down_revision: Union[str, Sequence[str], None] = '394e71379ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_pos_po_number'), 'material_pos', ['po_number'], unique=True)
    op.create_table('material_po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['material_pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_po_lines_po_id'), 'material_po_lines', ['po_id'], unique=False)
    op.add_column('raw_batches', sa.Column('material_po_line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'raw_batches', 'material_po_lines', ['material_po_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_batches', type_='foreignkey')
    op.drop_column('raw_batches', 'material_po_line_id')
    op.drop_index(op.f('ix_material_po_lines_po_id'), table_name='material_po_lines')
    op.drop_table('material_po_lines')
    op.drop_index(op.f('ix_material_pos_po_number'), table_name='material_pos')
    op.drop_table('material_pos')
    # ### end Alembic commands ###
