"""add users and lot to insection null = true

Revision ID: 37a032bdf637
Revises: bb1d44380f71
Create Date: 2026-01-11 13:29:54.455988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a032bdf637'
down_revision: Union[str, Sequence[str], None] = 'bb1d44380f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_inspections', 'traveler_step_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_inspections', 'traveler_step_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
