"""add length in mat po line

Revision ID: 3b79ac5d89c2
Revises: 0e52a98addf0
Create Date: 2025-10-15 16:54:48.888980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b79ac5d89c2'
down_revision: Union[str, Sequence[str], None] = '0e52a98addf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('heat_lot', sa.Text(), nullable=True))
    op.add_column('material_po_lines', sa.Column('size', sa.Text(), nullable=True))
    op.add_column('material_po_lines', sa.Column('length', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('material_po_lines', sa.Column('weight', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('material_po_lines', sa.Column('cert', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_po_lines', 'cert')
    op.drop_column('material_po_lines', 'weight')
    op.drop_column('material_po_lines', 'length')
    op.drop_column('material_po_lines', 'size')
    op.drop_column('material_po_lines', 'heat_lot')
    # ### end Alembic commands ###
