"""update traceler_nnullable in part table 

Revision ID: 3ffacf681db0
Revises: 2474ec727865
Create Date: 2025-10-03 14:07:20.747133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffacf681db0'
down_revision: Union[str, Sequence[str], None] = '2474ec727865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'unit_price')
    op.drop_column('purchase_orders', 'revision_id')
    op.drop_column('purchase_orders', 'po_id')
    op.drop_column('purchase_orders', 'due_date')
    op.drop_column('purchase_orders', 'qty_ordered')
    op.drop_column('purchase_orders', 'notes')
    op.drop_column('purchase_orders', 'part_id')
    op.alter_column('shop_travelers', 'traveler_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_travelers', 'traveler_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('purchase_orders', sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('notes', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('qty_ordered', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('due_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('unit_price', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
