"""add step_note

Revision ID: 406dc538b4f3
Revises: d7c12a3d5cf0
Create Date: 2025-10-05 20:36:01.511546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406dc538b4f3'
down_revision: Union[str, Sequence[str], None] = 'd7c12a3d5cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('break_entries', 'break_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('break_entries', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chemical_finishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_invoices', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customer_returns', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('holidays', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('holidays', 'pay_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inspection_records', 'is_fair',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('machine_schedule', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_machine_schedule_machine_id'), 'machine_schedule', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_schedule_traveler_step_id'), 'machine_schedule', ['traveler_step_id'], unique=False)
    op.drop_constraint(op.f('machine_schedule_traveler_step_id_fkey'), 'machine_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'machine_schedule', 'shop_traveler_steps', ['traveler_step_id'], ['id'])
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('material_pos', 'order_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('material_pos', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('measurement_devices', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mfg_processes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('part_revisions', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('parts', 'default_uom',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('parts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pay_periods', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pay_rates', 'ot_multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pay_rates', 'dt_multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('production_lots', 'planned_qty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('production_lots', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('production_lots', 'fair_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('raw_batches', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('raw_materials', 'uom',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('shop_traveler_steps', sa.Column('step_note', sa.Text(), nullable=True))
    op.alter_column('shop_traveler_steps', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qa_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_receive',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_accept',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_reject',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shop_travelers', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('step_machine_options_traveler_step_id_fkey'), 'step_machine_options', type_='foreignkey')
    op.create_foreign_key(None, 'step_machine_options', 'shop_traveler_steps', ['traveler_step_id'], ['id'])
    op.alter_column('subcon_order_lines', 'qty_planned',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_orders', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'qty_rejected',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'scrap_qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_receipts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_shipment_items', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcon_shipments', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_entries', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_leaves', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('time_leaves', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('time_leaves', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'approved'::character varying"),
               existing_nullable=False)
    op.alter_column('time_leaves', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('time_entries', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('subcon_shipments', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'shipped'::character varying"),
               existing_nullable=False)
    op.alter_column('subcon_shipment_items', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('subcon_receipts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'received'::character varying"),
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'scrap_qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'qty_rejected',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('subcon_receipt_items', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('subcon_orders', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('subcon_order_lines', 'qty_planned',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_constraint(None, 'step_machine_options', type_='foreignkey')
    op.create_foreign_key(op.f('step_machine_options_traveler_step_id_fkey'), 'step_machine_options', 'shop_traveler_steps', ['traveler_step_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shop_travelers', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_reject',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_accept',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qty_receive',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'qa_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('shop_traveler_steps', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('shop_traveler_steps', 'step_note')
    op.alter_column('raw_materials', 'uom',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'kg'::character varying"),
               existing_nullable=False)
    op.alter_column('raw_batches', 'qty_received',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('production_lots', 'fair_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('production_lots', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'in_process'::character varying"),
               existing_nullable=False)
    op.alter_column('production_lots', 'planned_qty',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pay_rates', 'dt_multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('2.0'),
               existing_nullable=False)
    op.alter_column('pay_rates', 'ot_multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               server_default=sa.text('1.5'),
               existing_nullable=False)
    op.alter_column('pay_periods', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('parts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=True)
    op.alter_column('parts', 'default_uom',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ea'::character varying"),
               existing_nullable=True)
    op.alter_column('part_revisions', 'is_current',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('mfg_processes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('measurement_devices', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'available'::character varying"),
               existing_nullable=False)
    op.alter_column('material_pos', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('material_pos', 'order_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'available'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'machine_schedule', type_='foreignkey')
    op.create_foreign_key(op.f('machine_schedule_traveler_step_id_fkey'), 'machine_schedule', 'shop_traveler_steps', ['traveler_step_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_machine_schedule_traveler_step_id'), table_name='machine_schedule')
    op.drop_index(op.f('ix_machine_schedule_machine_id'), table_name='machine_schedule')
    op.alter_column('machine_schedule', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=False)
    op.alter_column('inspection_records', 'is_fair',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('holidays', 'pay_multiplier',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text("'1'::numeric"),
               existing_nullable=False)
    op.alter_column('holidays', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('customer_returns', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'received'::character varying"),
               existing_nullable=False)
    op.alter_column('customer_invoices', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=False)
    op.alter_column('customer_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('chemical_finishes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('break_entries', 'is_paid',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('break_entries', 'break_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'lunch'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
