"""update table

Revision ID: 4131367ffb44
Revises: f5dfcf97397d
Create Date: 2025-12-25 16:34:41.641878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4131367ffb44'
down_revision: Union[str, Sequence[str], None] = 'f5dfcf97397d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_lines', sa.Column('third_due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('po_lines', sa.Column('status', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('purchase_orders', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'status')
    op.drop_column('purchase_orders', 'po_date')
    op.drop_column('po_lines', 'status')
    op.drop_column('po_lines', 'third_due_date')
    # ### end Alembic commands ###
