"""update tables

Revision ID: 441fd4ce09da
Revises: d6b1ff895a60
Create Date: 2026-05-01 09:58:38.215606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441fd4ce09da'
down_revision: Union[str, Sequence[str], None] = 'd6b1ff895a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('machines', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
