"""add is_paid to break_entries

Revision ID: 4d30f3029f0c
Revises: ff42a0f3a74a
Create Date: 2025-08-19 22:15:04.416502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d30f3029f0c'
down_revision: Union[str, Sequence[str], None] = 'ff42a0f3a74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_entries', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_entries', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
