"""add traveler template

Revision ID: 4f4cc28a091c
Revises: b430f91fecd7
Create Date: 2026-01-07 08:11:49.647912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4cc28a091c'
down_revision: Union[str, Sequence[str], None] = 'b430f91fecd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('step_detail', sa.String(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('qty_rework', sa.Numeric(precision=18, scale=3), nullable=True))
    op.alter_column('shop_traveler_steps', 'step_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('traveler_template_steps', sa.Column('step_detail', sa.Text(), nullable=True))
    op.alter_column('traveler_template_steps', 'step_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traveler_template_steps', 'step_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('traveler_template_steps', 'step_detail')
    op.alter_column('shop_traveler_steps', 'step_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shop_traveler_steps', 'qty_rework')
    op.drop_column('shop_traveler_steps', 'step_detail')
    # ### end Alembic commands ###
