"""link part to mfg_processes & chemical_finishes via selection tables

Revision ID: 52cac92553b7
Revises: 225617dee147
Create Date: 2025-09-25 09:53:59.096963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cac92553b7'
down_revision: Union[str, Sequence[str], None] = '225617dee147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemical_finishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_finishes_code'), 'chemical_finishes', ['code'], unique=True)
    op.create_table('mfg_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_processes_code'), 'mfg_processes', ['code'], unique=True)
    op.create_table('part_finish_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('finish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finish_id'], ['chemical_finishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'finish_id', name='uq_part_finish')
    )
    op.create_index(op.f('ix_part_finish_selections_finish_id'), 'part_finish_selections', ['finish_id'], unique=False)
    op.create_index(op.f('ix_part_finish_selections_part_id'), 'part_finish_selections', ['part_id'], unique=False)
    op.create_table('part_other_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_other_notes_part_id'), 'part_other_notes', ['part_id'], unique=False)
    op.create_table('part_process_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['mfg_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'process_id', name='uq_part_process')
    )
    op.create_index(op.f('ix_part_process_selections_part_id'), 'part_process_selections', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_process_selections_process_id'), 'part_process_selections', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_process_selections_process_id'), table_name='part_process_selections')
    op.drop_index(op.f('ix_part_process_selections_part_id'), table_name='part_process_selections')
    op.drop_table('part_process_selections')
    op.drop_index(op.f('ix_part_other_notes_part_id'), table_name='part_other_notes')
    op.drop_table('part_other_notes')
    op.drop_index(op.f('ix_part_finish_selections_part_id'), table_name='part_finish_selections')
    op.drop_index(op.f('ix_part_finish_selections_finish_id'), table_name='part_finish_selections')
    op.drop_table('part_finish_selections')
    op.drop_index(op.f('ix_mfg_processes_code'), table_name='mfg_processes')
    op.drop_table('mfg_processes')
    op.drop_index(op.f('ix_chemical_finishes_code'), table_name='chemical_finishes')
    op.drop_table('chemical_finishes')
    # ### end Alembic commands ###
