"""add lot qty shipment

Revision ID: 534d886a0652
Revises: aedd1555832b
Create Date: 2026-01-10 14:07:57.622744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534d886a0652'
down_revision: Union[str, Sequence[str], None] = 'aedd1555832b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('planned_ship_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'planned_ship_qty')
    # ### end Alembic commands ###
