"""add qr on traveler

Revision ID: 55220d2714c3
Revises: f1b204570816
Create Date: 2025-10-20 17:29:16.892321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55220d2714c3'
down_revision: Union[str, Sequence[str], None] = 'f1b204570816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_travelers', sa.Column('current_step_seq', sa.Integer(), nullable=True))
    op.add_column('shop_travelers', sa.Column('qr_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_shop_travelers_current_step_seq'), 'shop_travelers', ['current_step_seq'], unique=False)
    op.create_index(op.f('ix_shop_travelers_qr_code'), 'shop_travelers', ['qr_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_travelers_qr_code'), table_name='shop_travelers')
    op.drop_index(op.f('ix_shop_travelers_current_step_seq'), table_name='shop_travelers')
    op.drop_column('shop_travelers', 'qr_code')
    op.drop_column('shop_travelers', 'current_step_seq')
    # ### end Alembic commands ###
