"""update tables add operator name in icar

Revision ID: 56bd45a113f2
Revises: d96ea63770e9
Create Date: 2026-05-29 11:29:13.792228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bd45a113f2'
down_revision: Union[str, Sequence[str], None] = 'd96ea63770e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icars', sa.Column('operator_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icars', 'operator_name')
    # ### end Alembic commands ###
