"""remove lot_code from production_lots

Revision ID: 5766fea2bc25
Revises: e7e6100c1d5a
Create Date: 2025-08-25 21:55:56.011239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5766fea2bc25'
down_revision: Union[str, Sequence[str], None] = 'e7e6100c1d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('production_lots', sa.Column('lot_code', sa.String(), nullable=False))
    # op.create_index(op.f('ix_production_lots_lot_code'), 'production_lots', ['lot_code'], unique=True)
    # op.add_column('time_entries', sa.Column('work_user_id', sa.Integer(), nullable=True))
    # op.create_index('ix_time_entries_emp_work_week', 'time_entries', ['employee_id', 'work_user_id', 'clock_in_at'], unique=False)
    # op.create_index('ix_time_entries_work_user', 'time_entries', ['work_user_id'], unique=False)
    # op.create_index(op.f('ix_time_entries_work_user_id'), 'time_entries', ['work_user_id'], unique=False)
    # op.create_foreign_key(None, 'time_entries', 'users', ['work_user_id'], ['id'])
    # # ### end Alembic commands ###

    # ลบคอลัมน์ ถ้ามีอยู่
    op.execute("ALTER TABLE production_lots DROP COLUMN IF EXISTS lot_code")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_entries', type_='foreignkey')
    op.drop_index(op.f('ix_time_entries_work_user_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_work_user', table_name='time_entries')
    op.drop_index('ix_time_entries_emp_work_week', table_name='time_entries')
    op.drop_column('time_entries', 'work_user_id')
    op.drop_index(op.f('ix_production_lots_lot_code'), table_name='production_lots')
    op.drop_column('production_lots', 'lot_code')
    # ### end Alembic commands ###
