"""add RawBatchReference

Revision ID: 5a45fed6d284
Revises: 603909d87360
Create Date: 2026-07-02 11:32:43.271184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a45fed6d284'
down_revision: Union[str, Sequence[str], None] = '603909d87360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_batches', sa.Column('printed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'printed')
    # ### end Alembic commands ###
