"""add users and lot to insection

Revision ID: 5c545c7d70d2
Revises: 37a032bdf637
Create Date: 2026-01-11 13:38:01.526234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c545c7d70d2'
down_revision: Union[str, Sequence[str], None] = '37a032bdf637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_inspections_traveler_step_id'), table_name='qa_inspections')
    op.drop_constraint(op.f('qa_inspections_traveler_step_id_fkey'), 'qa_inspections', type_='foreignkey')
    op.drop_column('qa_inspections', 'traveler_step_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_inspections', sa.Column('traveler_step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('qa_inspections_traveler_step_id_fkey'), 'qa_inspections', 'shop_traveler_steps', ['traveler_step_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_qa_inspections_traveler_step_id'), 'qa_inspections', ['traveler_step_id'], unique=False)
    # ### end Alembic commands ###
