"""add type and spec in batch 

Revision ID: 5e149fb5683d
Revises: e3b062f6453b
Create Date: 2026-10-06 15:36:36.706554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e149fb5683d'
down_revision: Union[str, Sequence[str], None] = 'e3b062f6453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('raw_batches', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('raw_batches', sa.Column('spec_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_raw_batches_spec_id'), 'raw_batches', ['spec_id'], unique=False)
    op.create_index(op.f('ix_raw_batches_type_id'), 'raw_batches', ['type_id'], unique=False)
    op.create_foreign_key(None, 'raw_batches', 'material_specs', ['spec_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'raw_batches', 'material_types', ['type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_batches', type_='foreignkey')
    op.drop_constraint(None, 'raw_batches', type_='foreignkey')
    op.drop_index(op.f('ix_raw_batches_type_id'), table_name='raw_batches')
    op.drop_index(op.f('ix_raw_batches_spec_id'), table_name='raw_batches')
    op.drop_column('raw_batches', 'spec_id')
    op.drop_column('raw_batches', 'type_id')
    op.drop_table('material_types')
    op.drop_table('material_specs')
    # ### end Alembic commands ###
