"""add RawBatchReference

Revision ID: 603909d87360
Revises: 92774121b36f
Create Date: 2026-07-02 09:51:53.137211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603909d87360'
down_revision: Union[str, Sequence[str], None] = '92774121b36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_batch_reference'), 'raw_batch_references', type_='unique')
    op.create_unique_constraint('uq_batch_reference', 'raw_batch_references', ['batch_id', 'part_id', 'part_revision_id', 'po_id', 'lot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_batch_reference', 'raw_batch_references', type_='unique')
    op.create_unique_constraint(op.f('uq_batch_reference'), 'raw_batch_references', ['batch_id', 'part_revision_id', 'po_id', 'lot_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
