"""update ST

Revision ID: 63998f6f0114
Revises: e9d22a42f269
Create Date: 2026-04-25 11:20:30.452999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63998f6f0114'
down_revision: Union[str, Sequence[str], None] = 'e9d22a42f269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('supplier_po', sa.String(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('heat_lot', sa.String(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('material_size', sa.String(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('material_length', sa.String(), nullable=True))
    op.add_column('shop_travelers', sa.Column('materail', sa.String(), nullable=True))
    op.add_column('shop_travelers', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('traveler_template_steps', sa.Column('material_size', sa.String(), nullable=True))
    op.add_column('traveler_template_steps', sa.Column('material_length', sa.String(), nullable=True))
    op.add_column('traveler_templates', sa.Column('materail', sa.String(), nullable=True))
    op.add_column('traveler_templates', sa.Column('risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traveler_templates', 'risk_level')
    op.drop_column('traveler_templates', 'materail')
    op.drop_column('traveler_template_steps', 'material_length')
    op.drop_column('traveler_template_steps', 'material_size')
    op.drop_column('shop_travelers', 'risk_level')
    op.drop_column('shop_travelers', 'materail')
    op.drop_column('shop_traveler_steps', 'material_length')
    op.drop_column('shop_traveler_steps', 'material_size')
    op.drop_column('shop_traveler_steps', 'heat_lot')
    op.drop_column('shop_traveler_steps', 'supplier_name')
    op.drop_column('shop_traveler_steps', 'supplier_po')
    # ### end Alembic commands ###
