"""add lot po duedate

Revision ID: 67712f6ebc50
Revises: 12ae6ee30a1f
Create Date: 2026-01-13 10:33:03.288621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67712f6ebc50'
down_revision: Union[str, Sequence[str], None] = '12ae6ee30a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('lot_po_qty', sa.Integer(), nullable=True))
    op.add_column('production_lots', sa.Column('lot_po_duedate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'lot_po_duedate')
    op.drop_column('production_lots', 'lot_po_qty')
    # ### end Alembic commands ###
