"""update tables file_dir

Revision ID: 6aaa5d78ba1d
Revises: 9c45aa7d9e08
Create Date: 2026-06-02 12:01:49.757370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaa5d78ba1d'
down_revision: Union[str, Sequence[str], None] = '9c45aa7d9e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('file_dir', sa.String(), nullable=True))
    op.add_column('qa_inspection_templates', sa.Column('file_dir', sa.String(), nullable=True))
    op.add_column('qa_inspections', sa.Column('file_dir', sa.String(), nullable=True))
    op.add_column('shop_travelers', sa.Column('file_dir', sa.String(), nullable=True))
    op.add_column('traveler_templates', sa.Column('file_dir', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traveler_templates', 'file_dir')
    op.drop_column('shop_travelers', 'file_dir')
    op.drop_column('qa_inspections', 'file_dir')
    op.drop_column('qa_inspection_templates', 'file_dir')
    op.drop_column('production_lots', 'file_dir')
    # ### end Alembic commands ###
