"""update tables

Revision ID: 6b1d1a59172e
Revises: bcd3b074f152
Create Date: 2026-05-12 11:12:50.523140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1d1a59172e'
down_revision: Union[str, Sequence[str], None] = 'bcd3b074f152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_step_logs', sa.Column('materail_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_traveler_step_logs', 'materail_qty')
    # ### end Alembic commands ###
