"""add fields for material import

Revision ID: 6b5379c91b7e
Revises: a77630b48b65
Create Date: 2025-10-15 22:13:37.459314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5379c91b7e'
down_revision: Union[str, Sequence[str], None] = 'a77630b48b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('price_each', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('material_po_lines', sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('material_po_lines', sa.Column('cut_charge', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('material_po_lines', sa.Column('part_no', sa.String(), nullable=True))
    op.create_index(op.f('ix_material_po_lines_part_no'), 'material_po_lines', ['part_no'], unique=False)
    op.add_column('raw_batches', sa.Column('length_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'length_text')
    op.drop_index(op.f('ix_material_po_lines_part_no'), table_name='material_po_lines')
    op.drop_column('material_po_lines', 'part_no')
    op.drop_column('material_po_lines', 'cut_charge')
    op.drop_column('material_po_lines', 'total_price')
    op.drop_column('material_po_lines', 'price_each')
    # ### end Alembic commands ###
