"""add colume mat

Revision ID: 6fe0bbfe77a0
Revises: a95a2893b642
Create Date: 2025-10-15 13:00:01.985335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe0bbfe77a0'
down_revision: Union[str, Sequence[str], None] = 'a95a2893b642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_batches', sa.Column('heat_lot', sa.Text(), nullable=True))
    op.add_column('raw_batches', sa.Column('size', sa.Text(), nullable=True))
    op.add_column('raw_batches', sa.Column('length', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('raw_batches', sa.Column('weight', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('raw_batches', sa.Column('cert', sa.Text(), nullable=True))
    op.drop_column('raw_materials', 'cert')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('cert', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('raw_batches', 'cert')
    op.drop_column('raw_batches', 'weight')
    op.drop_column('raw_batches', 'length')
    op.drop_column('raw_batches', 'size')
    op.drop_column('raw_batches', 'heat_lot')
    # ### end Alembic commands ###
