"""update tables

Revision ID: 74b2f1b863e5
Revises: b6a3034a878f
Create Date: 2026-06-03 15:04:00.196144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b2f1b863e5'
down_revision: Union[str, Sequence[str], None] = 'b6a3034a878f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('from_lot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'from_lot')
    # ### end Alembic commands ###
