"""add backrefs on PO and add po_line link to ProductionLot

Revision ID: 7a9debeab78f
Revises: a8f073342979
Create Date: 2025-09-03 20:47:20.045543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9debeab78f'
down_revision: Union[str, Sequence[str], None] = 'a8f073342979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('po_line_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_production_lots_po_line_id'), 'production_lots', ['po_line_id'], unique=False)
    op.create_foreign_key(None, 'production_lots', 'po_lines', ['po_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_lots', type_='foreignkey')
    op.drop_index(op.f('ix_production_lots_po_line_id'), table_name='production_lots')
    op.drop_column('production_lots', 'po_line_id')
    # ### end Alembic commands ###
