"""add auto increasement 2

Revision ID: 7b9ab10e8cdd
Revises: 3fca01c7c077
Create Date: 2025-09-10 23:24:28.323588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9ab10e8cdd'
down_revision: Union[str, Sequence[str], None] = '3fca01c7c077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # เอา default/identity เดิมออกก่อน (กันกรณีเคยมี default แปลก ๆ)
    op.execute("""
        DO $$
        BEGIN
          BEGIN
            ALTER TABLE public.time_entries
              ALTER COLUMN id DROP DEFAULT;
          EXCEPTION WHEN undefined_object THEN
            -- ไม่มี DEFAULT ก็ข้าม
          END;
        END
        $$;

        -- ถ้าเคยเป็น identity แล้ว จะ error; จับไว้
        DO $$
        BEGIN
          BEGIN
            ALTER TABLE public.time_entries
              ALTER COLUMN id DROP IDENTITY IF EXISTS;
          EXCEPTION WHEN others THEN
            -- ข้าม
          END;
        END
        $$;

        -- ตั้งเป็น GENERATED BY DEFAULT AS IDENTITY
        ALTER TABLE public.time_entries
          ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    """)

    # ตั้งค่า start ให้มากกว่า MAX(id)
    op.execute("""
        SELECT setval(
          pg_get_serial_sequence('public.time_entries','id'),
          COALESCE((SELECT MAX(id) FROM public.time_entries),0) + 1,
          false
        );
    """)

def downgrade():
    # ถ้าต้องการย้อน กลับเป็นไม่มี identity (แล้วค่อยตั้ง DEFAULT/sequence เอง)
    op.execute("""
        ALTER TABLE public.time_entries
          ALTER COLUMN id DROP IDENTITY IF EXISTS;
    """)
