"""update tables raw_batches

Revision ID: 7baa9effa458
Revises: 997826a5ea2d
Create Date: 2026-06-11 15:54:47.006127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baa9effa458'
down_revision: Union[str, Sequence[str], None] = '997826a5ea2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_batches', sa.Column('mat_po', sa.Text(), nullable=True))
    op.add_column('raw_batches', sa.Column('cutting_note', sa.Text(), nullable=True))
    op.add_column('raw_batches', sa.Column('file_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'file_url')
    op.drop_column('raw_batches', 'cutting_note')
    op.drop_column('raw_batches', 'mat_po')
    # ### end Alembic commands ###
