"""add length text

Revision ID: 7c9f390e7494
Revises: d09ba29c20fb
Create Date: 2025-12-28 11:32:46.655395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9f390e7494'
down_revision: Union[str, Sequence[str], None] = 'd09ba29c20fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('length_text', sa.Text(), nullable=True))
    op.drop_column('material_po_lines', 'length_txet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('length_txet', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('material_po_lines', 'length_text')
    # ### end Alembic commands ###
