"""add users and lot to insection

Revision ID: 81f8b99d4588
Revises: 656e11fd5d1f
Create Date: 2026-01-11 13:28:08.672976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f8b99d4588'
down_revision: Union[str, Sequence[str], None] = '656e11fd5d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_inspections', sa.Column('lot_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_qa_inspections_lot_id'), 'qa_inspections', ['lot_id'], unique=False)
    op.create_foreign_key(None, 'qa_inspections', 'production_lots', ['lot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qa_inspections', type_='foreignkey')
    op.drop_index(op.f('ix_qa_inspections_lot_id'), table_name='qa_inspections')
    op.drop_column('qa_inspections', 'lot_id')
    # ### end Alembic commands ###
