"""add traveler no

Revision ID: 84f912c25c91
Revises: e01b9f739ad6
Create Date: 2025-10-02 23:33:14.258349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f912c25c91'
down_revision: Union[str, Sequence[str], None] = 'e01b9f739ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('shop_travelers', sa.Column('traveler_no', sa.String(), nullable=True))

    # fill values
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE shop_travelers
        SET traveler_no = 'TR-' || lpad(id::text, 5, '0')
        WHERE traveler_no IS NULL
    """))

    op.alter_column('shop_travelers', 'traveler_no', nullable=False)
    op.create_unique_constraint('uq_traveler_no', 'shop_travelers', ['traveler_no'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_travelers_traveler_no'), table_name='shop_travelers')
    op.drop_column('shop_travelers', 'traveler_no')
    # ### end Alembic commands ###
