"""update material in rev

Revision ID: 875a4543c570
Revises: 9b9c13ea5384
Create Date: 2026-05-06 22:03:13.162763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a4543c570'
down_revision: Union[str, Sequence[str], None] = '9b9c13ea5384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_revisions', sa.Column('material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_revisions', 'material')
    # ### end Alembic commands ###
