"""add customer 

Revision ID: 8a4db329c733
Revises: 1ee154dd0a23
Create Date: 2026-01-07 14:03:10.415683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4db329c733'
down_revision: Union[str, Sequence[str], None] = '1ee154dd0a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler_templates', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_traveler_templates_customer_id'), 'traveler_templates', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'traveler_templates', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'traveler_templates', type_='foreignkey')
    op.drop_index(op.f('ix_traveler_templates_customer_id'), table_name='traveler_templates')
    op.drop_column('traveler_templates', 'customer_id')
    # ### end Alembic commands ###
