"""add RawBatchReference

Revision ID: 92774121b36f
Revises: bb0a8ee757fa
Create Date: 2026-07-02 09:36:26.756894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92774121b36f'
down_revision: Union[str, Sequence[str], None] = 'bb0a8ee757fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_batch_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_revision_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['raw_batches.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'part_revision_id', 'po_id', 'lot_id', name='uq_batch_reference')
    )
    op.create_index(op.f('ix_raw_batch_references_batch_id'), 'raw_batch_references', ['batch_id'], unique=False)
    op.create_index(op.f('ix_raw_batch_references_lot_id'), 'raw_batch_references', ['lot_id'], unique=False)
    op.create_index(op.f('ix_raw_batch_references_part_id'), 'raw_batch_references', ['part_id'], unique=False)
    op.create_index(op.f('ix_raw_batch_references_part_revision_id'), 'raw_batch_references', ['part_revision_id'], unique=False)
    op.create_index(op.f('ix_raw_batch_references_po_id'), 'raw_batch_references', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_batch_references_po_id'), table_name='raw_batch_references')
    op.drop_index(op.f('ix_raw_batch_references_part_revision_id'), table_name='raw_batch_references')
    op.drop_index(op.f('ix_raw_batch_references_part_id'), table_name='raw_batch_references')
    op.drop_index(op.f('ix_raw_batch_references_lot_id'), table_name='raw_batch_references')
    op.drop_index(op.f('ix_raw_batch_references_batch_id'), table_name='raw_batch_references')
    op.drop_table('raw_batch_references')
    # ### end Alembic commands ###
