"""update tables last activity in production lot

Revision ID: 997826a5ea2d
Revises: 74b2f1b863e5
Create Date: 2026-06-05 08:31:43.162840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997826a5ea2d'
down_revision: Union[str, Sequence[str], None] = '74b2f1b863e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'last_activity')
    # ### end Alembic commands ###
