"""update tables

Revision ID: 9b9c13ea5384
Revises: aa46b96e62f7
Create Date: 2026-05-06 21:01:35.650643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9c13ea5384'
down_revision: Union[str, Sequence[str], None] = 'aa46b96e62f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traveler_templates', sa.Column('material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traveler_templates', 'material')
    # ### end Alembic commands ###
