"""update tables add ECAR

Revision ID: 9c45aa7d9e08
Revises: 56bd45a113f2
Create Date: 2026-05-29 14:54:47.621441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c45aa7d9e08'
down_revision: Union[str, Sequence[str], None] = '56bd45a113f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecars', sa.Column('lot_no', sa.String(), nullable=True))
    op.add_column('ecars', sa.Column('part_name', sa.String(), nullable=True))
    op.add_column('ecars', sa.Column('icar_idr', sa.String(), nullable=True))
    op.add_column('ecars', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('ecars', sa.Column('reject_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('ecars', sa.Column('reject_percent', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecars', 'reject_percent')
    op.drop_column('ecars', 'reject_qty')
    op.drop_column('ecars', 'issue_date')
    op.drop_column('ecars', 'icar_idr')
    op.drop_column('ecars', 'part_name')
    op.drop_column('ecars', 'lot_no')
    # ### end Alembic commands ###
