"""update tables

Revision ID: 9e50f2df3f09
Revises: 6b1d1a59172e
Create Date: 2026-05-12 11:59:12.704103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e50f2df3f09'
down_revision: Union[str, Sequence[str], None] = '6b1d1a59172e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_step_logs', sa.Column('material_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    op.drop_column('shop_traveler_step_logs', 'materail_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_step_logs', sa.Column('materail_qty', sa.NUMERIC(precision=18, scale=3), autoincrement=False, nullable=True))
    op.drop_column('shop_traveler_step_logs', 'material_qty')
    # ### end Alembic commands ###
