"""update inventory

Revision ID: 9fad79293903
Revises: 6b0457dc9c26
Create Date: 2026-08-03 13:08:12.924917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad79293903'
down_revision: Union[str, Sequence[str], None] = '6b0457dc9c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('qty_produced', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('inventory', sa.Column('qty_shipped', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('inventory', sa.Column('qty_scrap', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('inventory', sa.Column('qty_adjust', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('inventory', sa.Column('qty_on_hand', sa.Numeric(precision=18, scale=3), server_default=sa.text('0'), nullable=False))
    op.add_column('inventory', sa.Column('counted_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('inventory', sa.Column('counted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('inventory', sa.Column('inventory_status', sa.String(), server_default=sa.text("'normal'"), nullable=False))
    op.drop_constraint(op.f('inventory_lot_id_key'), 'inventory', type_='unique')
    op.create_index(op.f('ix_inventory_lot_id'), 'inventory', ['lot_id'], unique=True)
    op.drop_constraint(op.f('inventory_lot_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'production_lots', ['lot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory', 'ship_qty')
    op.drop_column('inventory', 'prod_qty')
    op.drop_column('inventory', 'note')
    op.drop_column('inventory', 'stock_qty')
    op.add_column('production_lots', sa.Column('completed_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'completed_qty')
    op.add_column('inventory', sa.Column('stock_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('prod_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('ship_qty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_lot_id_fkey'), 'inventory', 'production_lots', ['lot_id'], ['id'])
    op.drop_index(op.f('ix_inventory_lot_id'), table_name='inventory')
    op.create_unique_constraint(op.f('inventory_lot_id_key'), 'inventory', ['lot_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventory', 'inventory_status')
    op.drop_column('inventory', 'updated_at')
    op.drop_column('inventory', 'counted_at')
    op.drop_column('inventory', 'counted_qty')
    op.drop_column('inventory', 'qty_on_hand')
    op.drop_column('inventory', 'qty_adjust')
    op.drop_column('inventory', 'qty_scrap')
    op.drop_column('inventory', 'qty_shipped')
    op.drop_column('inventory', 'qty_produced')
    # ### end Alembic commands ###
