"""add uom on shop step

Revision ID: 9fd2dd9a2b86
Revises: 55220d2714c3
Create Date: 2025-10-20 19:17:41.244442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd2dd9a2b86'
down_revision: Union[str, Sequence[str], None] = '55220d2714c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('uom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_traveler_steps', 'uom')
    # ### end Alembic commands ###
