"""qty

Revision ID: a3859b199f9e
Revises: 52cac92553b7
Create Date: 2025-09-25 11:25:33.494624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3859b199f9e'
down_revision: Union[str, Sequence[str], None] = '52cac92553b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lot_material_use_batch_id'), 'lot_material_use', ['batch_id'], unique=False)
    op.create_index(op.f('ix_lot_material_use_lot_id'), 'lot_material_use', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_material_use_lot_id'), table_name='lot_material_use')
    op.drop_index(op.f('ix_lot_material_use_batch_id'), table_name='lot_material_use')
    # ### end Alembic commands ###
