"""add size text

Revision ID: a77630b48b65
Revises: 3b79ac5d89c2
Create Date: 2025-10-15 17:56:49.618956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77630b48b65'
down_revision: Union[str, Sequence[str], None] = '3b79ac5d89c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('size_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'size_text')
    # ### end Alembic commands ###
