"""add PO line, shipment, invoice, material PO models

Revision ID: a8f073342979
Revises: fb48a470a02f
Create Date: 2025-09-03 20:37:00.994036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f073342979'
down_revision: Union[str, Sequence[str], None] = 'fb48a470a02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_invoices_invoice_no'), 'customer_invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_customer_invoices_po_id'), 'customer_invoices', ['po_id'], unique=False)
    op.create_table('customer_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.Column('ship_to', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('tracking_no', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_shipments_po_id'), 'customer_shipments', ['po_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('qty_ordered', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['part_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_lines_po', 'po_lines', ['po_id'], unique=False)
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('customer_shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['customer_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_shipment_items_lot_id'), 'customer_shipment_items', ['lot_id'], unique=False)
    op.create_index(op.f('ix_customer_shipment_items_po_line_id'), 'customer_shipment_items', ['po_line_id'], unique=False)
    op.create_index(op.f('ix_customer_shipment_items_shipment_id'), 'customer_shipment_items', ['shipment_id'], unique=False)
    op.create_table('customer_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('shipment_item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['customer_invoices.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['shipment_item_id'], ['customer_shipment_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_invoice_lines_invoice_id'), 'customer_invoice_lines', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_invoice_lines_invoice_id'), table_name='customer_invoice_lines')
    op.drop_table('customer_invoice_lines')
    op.drop_index(op.f('ix_customer_shipment_items_shipment_id'), table_name='customer_shipment_items')
    op.drop_index(op.f('ix_customer_shipment_items_po_line_id'), table_name='customer_shipment_items')
    op.drop_index(op.f('ix_customer_shipment_items_lot_id'), table_name='customer_shipment_items')
    op.drop_table('customer_shipment_items')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_index('ix_po_lines_po', table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_customer_shipments_po_id'), table_name='customer_shipments')
    op.drop_table('customer_shipments')
    op.drop_index(op.f('ix_customer_invoices_po_id'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_invoice_no'), table_name='customer_invoices')
    op.drop_table('customer_invoices')
    # ### end Alembic commands ###
