"""add colume mat

Revision ID: a95a2893b642
Revises: 006d555b3fd2
Create Date: 2025-10-15 12:58:30.434017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95a2893b642'
down_revision: Union[str, Sequence[str], None] = '006d555b3fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('type', sa.String(), nullable=True))
    op.add_column('raw_materials', sa.Column('cert', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'cert')
    op.drop_column('raw_materials', 'type')
    # ### end Alembic commands ###
