"""add customer return

Revision ID: aed3e6e0b960
Revises: 9f1c62e492b7
Create Date: 2025-09-05 14:18:25.102009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed3e6e0b960'
down_revision: Union[str, Sequence[str], None] = '9f1c62e492b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('rma_no', sa.String(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_returns_po_id'), 'customer_returns', ['po_id'], unique=False)
    op.create_index(op.f('ix_customer_returns_rma_no'), 'customer_returns', ['rma_no'], unique=True)
    op.create_table('customer_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('shipment_item_id', sa.Integer(), nullable=True),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['production_lots.id'], ),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['customer_returns.id'], ),
    sa.ForeignKeyConstraint(['shipment_item_id'], ['customer_shipment_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_return_items_lot_id'), 'customer_return_items', ['lot_id'], unique=False)
    op.create_index(op.f('ix_customer_return_items_po_line_id'), 'customer_return_items', ['po_line_id'], unique=False)
    op.create_index(op.f('ix_customer_return_items_return_id'), 'customer_return_items', ['return_id'], unique=False)
    op.create_index(op.f('ix_customer_return_items_shipment_item_id'), 'customer_return_items', ['shipment_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_return_items_shipment_item_id'), table_name='customer_return_items')
    op.drop_index(op.f('ix_customer_return_items_return_id'), table_name='customer_return_items')
    op.drop_index(op.f('ix_customer_return_items_po_line_id'), table_name='customer_return_items')
    op.drop_index(op.f('ix_customer_return_items_lot_id'), table_name='customer_return_items')
    op.drop_table('customer_return_items')
    op.drop_index(op.f('ix_customer_returns_rma_no'), table_name='customer_returns')
    op.drop_index(op.f('ix_customer_returns_po_id'), table_name='customer_returns')
    op.drop_table('customer_returns')
    # ### end Alembic commands ###
