"""add op_no

Revision ID: aeed57f10f51
Revises: 5c545c7d70d2
Create Date: 2026-01-11 13:58:46.937633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeed57f10f51'
down_revision: Union[str, Sequence[str], None] = '5c545c7d70d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_inspection_items', sa.Column('op_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_inspection_items', 'op_no')
    # ### end Alembic commands ###
