"""add raw

Revision ID: b2b5cb14b374
Revises: 22b3c00d9d3a
Create Date: 2026-07-03 13:30:54.486110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b5cb14b374'
down_revision: Union[str, Sequence[str], None] = '22b3c00d9d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_batches', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('raw_batches', sa.Column('heat_po', sa.String(), nullable=True))
    op.add_column('raw_batches', sa.Column('heat_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'heat_type')
    op.drop_column('raw_batches', 'heat_po')
    op.drop_column('raw_batches', 'date_created')
    # ### end Alembic commands ###
