"""add traveler template

Revision ID: b430f91fecd7
Revises: 7c9f390e7494
Create Date: 2026-01-06 22:53:09.723297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b430f91fecd7'
down_revision: Union[str, Sequence[str], None] = '7c9f390e7494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_revision_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['part_revision_id'], ['part_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'part_revision_id', 'version', name='uq_template_part_rev_version')
    )
    op.create_index('ix_traveler_templates_active', 'traveler_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_traveler_templates_part_id'), 'traveler_templates', ['part_id'], unique=False)
    op.create_index(op.f('ix_traveler_templates_part_revision_id'), 'traveler_templates', ['part_revision_id'], unique=False)
    op.create_table('traveler_template_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('station', sa.String(), nullable=True),
    sa.Column('qa_required', sa.Boolean(), nullable=False),
    sa.Column('default_uom', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['traveler_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'seq', name='uq_template_seq')
    )
    op.create_index('ix_template_steps_station', 'traveler_template_steps', ['station'], unique=False)
    op.create_index(op.f('ix_traveler_template_steps_template_id'), 'traveler_template_steps', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traveler_template_steps_template_id'), table_name='traveler_template_steps')
    op.drop_index('ix_template_steps_station', table_name='traveler_template_steps')
    op.drop_table('traveler_template_steps')
    op.drop_index(op.f('ix_traveler_templates_part_revision_id'), table_name='traveler_templates')
    op.drop_index(op.f('ix_traveler_templates_part_id'), table_name='traveler_templates')
    op.drop_index('ix_traveler_templates_active', table_name='traveler_templates')
    op.drop_table('traveler_templates')
    # ### end Alembic commands ###
