"""update tables file_dir

Revision ID: b6a3034a878f
Revises: 6aaa5d78ba1d
Create Date: 2026-06-02 12:04:11.589987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a3034a878f'
down_revision: Union[str, Sequence[str], None] = '6aaa5d78ba1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_lots', 'date_closed')
    # ### end Alembic commands ###
