"""update tables

Revision ID: bcd3b074f152
Revises: 875a4543c570
Create Date: 2026-05-11 11:07:57.153900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd3b074f152'
down_revision: Union[str, Sequence[str], None] = '875a4543c570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_po', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_lot', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_send_date', sa.Date(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('supplier_receive_date', sa.Date(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('material_size', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('material_length', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('material_uom', sa.String(), nullable=True))
    op.add_column('shop_traveler_step_logs', sa.Column('material_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_shop_traveler_step_logs_supplier_id'), 'shop_traveler_step_logs', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'shop_traveler_step_logs', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_traveler_step_logs', type_='foreignkey')
    op.drop_index(op.f('ix_shop_traveler_step_logs_supplier_id'), table_name='shop_traveler_step_logs')
    op.drop_column('shop_traveler_step_logs', 'material_type')
    op.drop_column('shop_traveler_step_logs', 'material_uom')
    op.drop_column('shop_traveler_step_logs', 'material_length')
    op.drop_column('shop_traveler_step_logs', 'material_size')
    op.drop_column('shop_traveler_step_logs', 'supplier_receive_date')
    op.drop_column('shop_traveler_step_logs', 'supplier_send_date')
    op.drop_column('shop_traveler_step_logs', 'supplier_id')
    op.drop_column('shop_traveler_step_logs', 'supplier_lot')
    op.drop_column('shop_traveler_step_logs', 'supplier_name')
    op.drop_column('shop_traveler_step_logs', 'supplier_po')
    # ### end Alembic commands ###
