"""add tables

Revision ID: bdccfca8a7b8
Revises: 27dcf0d9dea6
Create Date: 2025-12-28 11:22:43.275957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdccfca8a7b8'
down_revision: Union[str, Sequence[str], None] = '27dcf0d9dea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('qty_uom', sa.String(), nullable=True))
    op.add_column('material_po_lines', sa.Column('size_uom', sa.String(), nullable=True))
    op.add_column('material_po_lines', sa.Column('length_uom', sa.String(), nullable=True))
    op.add_column('raw_materials', sa.Column('size_uom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'size_uom')
    op.drop_column('material_po_lines', 'length_uom')
    op.drop_column('material_po_lines', 'size_uom')
    op.drop_column('material_po_lines', 'qty_uom')
    # ### end Alembic commands ###
