"""add lot not in shipment

Revision ID: c0bd4554d7cc
Revises: ddc97233532c
Create Date: 2025-11-03 19:27:22.130460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0bd4554d7cc'
down_revision: Union[str, Sequence[str], None] = 'ddc97233532c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_shipments', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer_shipments', 'production_lots', ['lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_shipments', type_='foreignkey')
    op.drop_column('customer_shipments', 'lot_id')
    # ### end Alembic commands ###
