"""part mat update

Revision ID: c63becad335c
Revises: b10de5ed2126
Create Date: 2025-09-26 11:03:57.733881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63becad335c'
down_revision: Union[str, Sequence[str], None] = 'b10de5ed2126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_materials', sa.Column('raw_material_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_part_materials_raw_material_id'), 'part_materials', ['raw_material_id'], unique=False)
    op.create_unique_constraint('uq_part_material_once', 'part_materials', ['part_id', 'raw_material_id'])
    op.create_foreign_key(None, 'part_materials', 'raw_materials', ['raw_material_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('part_materials', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_materials', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'part_materials', type_='foreignkey')
    op.drop_constraint('uq_part_material_once', 'part_materials', type_='unique')
    op.drop_index(op.f('ix_part_materials_raw_material_id'), table_name='part_materials')
    op.drop_column('part_materials', 'raw_material_id')
    # ### end Alembic commands ###
