"""update tables

Revision ID: c8edb934bca8
Revises: 441fd4ce09da
Create Date: 2026-05-04 21:14:29.978958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8edb934bca8'
down_revision: Union[str, Sequence[str], None] = '441fd4ce09da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # 1 add column
    op.add_column(
        'qa_inspection_templates',
        sa.Column('version', sa.Integer(), nullable=True)
    )

    # 2 assign version แบบไม่ซ้ำ
    op.execute("""
    WITH ranked AS (
      SELECT id,
             ROW_NUMBER() OVER (
               PARTITION BY part_id, rev_id
               ORDER BY created_at
             ) AS rn
      FROM qa_inspection_templates
    )
    UPDATE qa_inspection_templates t
    SET version = ranked.rn
    FROM ranked
    WHERE t.id = ranked.id;
    """)

    # 3 set not null
    op.alter_column('qa_inspection_templates', 'version', nullable=False)

    # 4 create constraint
    op.create_unique_constraint(
        'uq_template_version',
        'qa_inspection_templates',
        ['part_id', 'rev_id', 'version']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_template_version', 'qa_inspection_templates', type_='unique')
    op.drop_index(op.f('ix_qa_inspection_templates_active'), table_name='qa_inspection_templates')
    op.drop_column('qa_inspection_templates', 'version')
    # ### end Alembic commands ###
