"""update parts tables

Revision ID: cb7f68c2b8b7
Revises: f274a7f300da
Create Date: 2026-08-24 11:32:14.609797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7f68c2b8b7'
down_revision: Union[str, Sequence[str], None] = 'f274a7f300da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('part_detail_extra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'part_detail_extra')
    # ### end Alembic commands ###
