"""add table atomic

Revision ID: cdad821dd4b3
Revises: f2fb197a2b54
Create Date: 2025-10-07 22:21:02.408435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdad821dd4b3'
down_revision: Union[str, Sequence[str], None] = 'f2fb197a2b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_doc_counters_type_year', 'doc_counters', ['doc_type', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_doc_counters_type_year', 'doc_counters', type_='unique')
    # ### end Alembic commands ###
