"""add lot allocate

Revision ID: ce4b08dc7abd
Revises: c0bd4554d7cc
Create Date: 2025-11-29 21:12:49.724214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4b08dc7abd'
down_revision: Union[str, Sequence[str], None] = 'c0bd4554d7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_shipment_items', sa.Column('lot_allocate_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_shipment_items_lot_allocate_id'), 'customer_shipment_items', ['lot_allocate_id'], unique=False)
    op.create_foreign_key(None, 'customer_shipment_items', 'production_lots', ['lot_allocate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_shipment_items', type_='foreignkey')
    op.drop_index(op.f('ix_customer_shipment_items_lot_allocate_id'), table_name='customer_shipment_items')
    op.drop_column('customer_shipment_items', 'lot_allocate_id')
    # ### end Alembic commands ###
