"""add emp op

Revision ID: ce9672aa5c86
Revises: 67712f6ebc50
Create Date: 2026-01-17 14:22:22.163316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9672aa5c86'
down_revision: Union[str, Sequence[str], None] = '67712f6ebc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emp_op', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['emp_op'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'emp_op')
    # ### end Alembic commands ###
