"""add mat no

Revision ID: d04b30c1feb9
Revises: d5dc43ee15e0
Create Date: 2025-10-15 16:21:03.265765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04b30c1feb9'
down_revision: Union[str, Sequence[str], None] = 'd5dc43ee15e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_pos', sa.Column('mat_no', sa.String(), nullable=False))
    op.alter_column('material_pos', 'po_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_material_pos_po_number'), table_name='material_pos')
    op.create_index(op.f('ix_material_pos_po_number'), 'material_pos', ['po_number'], unique=False)
    op.create_index(op.f('ix_material_pos_mat_no'), 'material_pos', ['mat_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_pos_mat_no'), table_name='material_pos')
    op.drop_index(op.f('ix_material_pos_po_number'), table_name='material_pos')
    op.create_index(op.f('ix_material_pos_po_number'), 'material_pos', ['po_number'], unique=True)
    op.alter_column('material_pos', 'po_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('material_pos', 'mat_no')
    # ### end Alembic commands ###
