"""add length text

Revision ID: d09ba29c20fb
Revises: cd9f10a7d6d6
Create Date: 2025-12-28 11:29:38.895179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09ba29c20fb'
down_revision: Union[str, Sequence[str], None] = 'cd9f10a7d6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_po_lines', sa.Column('size_text', sa.Text(), nullable=True))
    op.add_column('material_po_lines', sa.Column('length_txet', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_po_lines', 'length_txet')
    op.drop_column('material_po_lines', 'size_text')
    # ### end Alembic commands ###
