"""add init and qa

Revision ID: d131c9523501
Revises: f575975be2ee
Create Date: 2026-04-27 15:52:57.578748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd131c9523501'
down_revision: Union[str, Sequence[str], None] = 'f575975be2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('operator_init_id', sa.Integer(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('operator_qa_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shop_traveler_steps_operator_init_id'), 'shop_traveler_steps', ['operator_init_id'], unique=False)
    op.create_index(op.f('ix_shop_traveler_steps_operator_qa_id'), 'shop_traveler_steps', ['operator_qa_id'], unique=False)
    op.create_foreign_key(None, 'shop_traveler_steps', 'employees', ['operator_init_id'], ['id'])
    op.create_foreign_key(None, 'shop_traveler_steps', 'employees', ['operator_qa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_traveler_steps', type_='foreignkey')
    op.drop_constraint(None, 'shop_traveler_steps', type_='foreignkey')
    op.drop_index(op.f('ix_shop_traveler_steps_operator_qa_id'), table_name='shop_traveler_steps')
    op.drop_index(op.f('ix_shop_traveler_steps_operator_init_id'), table_name='shop_traveler_steps')
    op.drop_column('shop_traveler_steps', 'operator_qa_id')
    op.drop_column('shop_traveler_steps', 'operator_init_id')
    # ### end Alembic commands ###
