"""move col

Revision ID: d3d12ef61259
Revises: c2c4fb3e07a4
Create Date: 2025-09-03 21:25:33.881780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d12ef61259'
down_revision: Union[str, Sequence[str], None] = 'c2c4fb3e07a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_insp_rec_part_rev'), 'inspection_records', type_='foreignkey')
    op.create_foreign_key(None, 'inspection_records', 'part_revisions', ['part_revision_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_production_lots_po_line_id'), table_name='production_lots')
    op.create_index(op.f('ix_production_lots_part_revision_id'), 'production_lots', ['part_revision_id'], unique=False)
    op.create_index(op.f('ix_production_lots_po_id'), 'production_lots', ['po_id'], unique=False)
    op.drop_constraint(op.f('production_lots_po_line_id_fkey'), 'production_lots', type_='foreignkey')
    op.drop_column('production_lots', 'po_line_id')
    op.create_index(op.f('ix_time_entries_payroll_emp_id'), 'time_entries', ['payroll_emp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_payroll_emp_id'), table_name='time_entries')
    op.add_column('production_lots', sa.Column('po_line_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('production_lots_po_line_id_fkey'), 'production_lots', 'po_lines', ['po_line_id'], ['id'])
    op.drop_index(op.f('ix_production_lots_po_id'), table_name='production_lots')
    op.drop_index(op.f('ix_production_lots_part_revision_id'), table_name='production_lots')
    op.create_index(op.f('ix_production_lots_po_line_id'), 'production_lots', ['po_line_id'], unique=False)
    op.drop_constraint(None, 'inspection_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_insp_rec_part_rev'), 'inspection_records', 'part_revisions', ['part_revision_id'], ['id'])
    # ### end Alembic commands ###
