"""add size

Revision ID: d5dc43ee15e0
Revises: fcb32b3218b9
Create Date: 2025-10-15 16:12:15.841962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5dc43ee15e0'
down_revision: Union[str, Sequence[str], None] = 'fcb32b3218b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_materials', sa.Column('size', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials', 'size')
    # ### end Alembic commands ###
