"""add nickname and lastname

Revision ID: de167301214f
Revises: ce9672aa5c86
Create Date: 2026-01-17 14:23:45.196401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de167301214f'
down_revision: Union[str, Sequence[str], None] = 'ce9672aa5c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('lastname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'lastname')
    op.drop_column('employees', 'nickname')
    # ### end Alembic commands ###
