"""empty message

Revision ID: dfbffa351b6b
Revises: 1d415228c202
Create Date: 2025-08-27 09:12:33.091244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbffa351b6b'
down_revision: Union[str, Sequence[str], None] = '1d415228c202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pay_rates_emp_eff', 'pay_rates', ['employee_id', 'effective_from'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pay_rates_emp_eff', 'pay_rates', type_='unique')
    # ### end Alembic commands ###
