"""update tables is_lasted

Revision ID: e5c19ce54ce2
Revises: c8edb934bca8
Create Date: 2026-05-04 21:37:25.722115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c19ce54ce2'
down_revision: Union[str, Sequence[str], None] = 'c8edb934bca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # =========================
    # QA TEMPLATE
    # =========================

    # 1️⃣ เพิ่ม column ก่อน (nullable)
    op.add_column(
        'qa_inspection_templates',
        sa.Column('is_latest', sa.Boolean(), nullable=True)
    )

    # 2️⃣ set ค่า default ให้ข้อมูลเก่า
    op.execute("""
        UPDATE qa_inspection_templates
        SET is_latest = FALSE
        WHERE is_latest IS NULL
    """)

    # 3️⃣ set NOT NULL
    op.alter_column(
        'qa_inspection_templates',
        'is_latest',
        nullable=False
    )

    # 4️⃣ index
    op.create_index(
        op.f('ix_qa_inspection_templates_is_latest'),
        'qa_inspection_templates',
        ['is_latest'],
        unique=False
    )

    # =========================
    # TRAVELER TEMPLATE
    # =========================

    op.add_column(
        'traveler_templates',
        sa.Column('is_latest', sa.Boolean(), nullable=True)
    )

    op.execute("""
        UPDATE traveler_templates
        SET is_latest = FALSE
        WHERE is_latest IS NULL
    """)

    op.alter_column(
        'traveler_templates',
        'is_latest',
        nullable=False
    )

    op.create_index(
        op.f('ix_traveler_templates_is_latest'),
        'traveler_templates',
        ['is_latest'],
        unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traveler_templates_is_latest'), table_name='traveler_templates')
    op.drop_column('traveler_templates', 'is_latest')
    op.drop_index(op.f('ix_qa_inspection_templates_is_latest'), table_name='qa_inspection_templates')
    op.drop_index(op.f('ix_qa_inspection_templates_active'), table_name='qa_inspection_templates')
    op.drop_column('qa_inspection_templates', 'is_latest')
    # ### end Alembic commands ###
