"""add po line to productionlot

Revision ID: e6ae4e9748a6
Revises: d5291a3fa6c4
Create Date: 2025-09-08 18:27:01.399353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ae4e9748a6'
down_revision: Union[str, Sequence[str], None] = 'd5291a3fa6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('po_line_id', sa.Integer(), nullable=True))
    op.add_column('production_lots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_production_lots_po_line_id'), 'production_lots', ['po_line_id'], unique=False)
    op.create_foreign_key(None, 'production_lots', 'po_lines', ['po_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_lots', type_='foreignkey')
    op.drop_index(op.f('ix_production_lots_po_line_id'), table_name='production_lots')
    op.drop_column('production_lots', 'created_at')
    op.drop_column('production_lots', 'po_line_id')
    # ### end Alembic commands ###
