"""update po note

Revision ID: eb827819b5e4
Revises: 7baa9effa458
Create Date: 2026-06-11 16:50:45.044741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb827819b5e4'
down_revision: Union[str, Sequence[str], None] = '7baa9effa458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_batches', sa.Column('po_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'po_note')
    # ### end Alembic commands ###
