"""rename leave entry

Revision ID: ecdecc81ef8a
Revises: fd6dc824013a
Create Date: 2025-09-05 22:48:57.761573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecdecc81ef8a'
down_revision: Union[str, Sequence[str], None] = 'fd6dc824013a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_leaves_emp_date', 'time_leaves', ['employee_id', 'start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_time_leaves_employee_id'), 'time_leaves', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_leave_emp_date'), table_name='leave_entries')
    op.drop_index(op.f('ix_leave_entries_employee_id'), table_name='leave_entries')
    op.drop_table('leave_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('leave_entries_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_entries_pkey'))
    )
    op.create_index(op.f('ix_leave_entries_employee_id'), 'leave_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_emp_date'), 'leave_entries', ['employee_id', 'start_at', 'end_at'], unique=False)
    op.drop_index(op.f('ix_time_leaves_employee_id'), table_name='time_leaves')
    op.drop_index('ix_time_leaves_emp_date', table_name='time_leaves')
    op.drop_table('time_leaves')
    # ### end Alembic commands ###
