"""add inspection template

Revision ID: f515b06b2cc4
Revises: 4f4cc28a091c
Create Date: 2026-01-07 11:37:53.200257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f515b06b2cc4'
down_revision: Union[str, Sequence[str], None] = '4f4cc28a091c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_inspection_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('rev_id', sa.Integer(), nullable=True),
    sa.Column('step_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['rev_id'], ['part_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_inspection_templates_part_id'), 'qa_inspection_templates', ['part_id'], unique=False)
    op.create_index(op.f('ix_qa_inspection_templates_rev_id'), 'qa_inspection_templates', ['rev_id'], unique=False)
    op.create_table('qa_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traveler_step_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['traveler_step_id'], ['shop_traveler_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_inspections_traveler_step_id'), 'qa_inspections', ['traveler_step_id'], unique=False)
    op.create_table('qa_inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('bb_no', sa.String(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('tqw', sa.String(), nullable=True),
    sa.Column('fa', sa.Boolean(), nullable=True),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('qa_time_stamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['qa_inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'seq', name='uq_inspection_seq')
    )
    op.create_index(op.f('ix_qa_inspection_items_inspection_id'), 'qa_inspection_items', ['inspection_id'], unique=False)
    op.create_table('qa_inspection_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('bb_no', sa.String(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['qa_inspection_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'seq', name='uq_qa_template_seq')
    )
    op.create_index(op.f('ix_qa_inspection_template_items_template_id'), 'qa_inspection_template_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_inspection_template_items_template_id'), table_name='qa_inspection_template_items')
    op.drop_table('qa_inspection_template_items')
    op.drop_index(op.f('ix_qa_inspection_items_inspection_id'), table_name='qa_inspection_items')
    op.drop_table('qa_inspection_items')
    op.drop_index(op.f('ix_qa_inspections_traveler_step_id'), table_name='qa_inspections')
    op.drop_table('qa_inspections')
    op.drop_index(op.f('ix_qa_inspection_templates_rev_id'), table_name='qa_inspection_templates')
    op.drop_index(op.f('ix_qa_inspection_templates_part_id'), table_name='qa_inspection_templates')
    op.drop_table('qa_inspection_templates')
    # ### end Alembic commands ###
