"""add init and qa

Revision ID: f575975be2ee
Revises: 63998f6f0114
Create Date: 2026-04-27 15:45:40.049028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f575975be2ee'
down_revision: Union[str, Sequence[str], None] = '63998f6f0114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('operator__init_id', sa.Integer(), nullable=True))
    op.add_column('shop_traveler_steps', sa.Column('operator__qa_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shop_traveler_steps_operator__init_id'), 'shop_traveler_steps', ['operator__init_id'], unique=False)
    op.create_index(op.f('ix_shop_traveler_steps_operator__qa_id'), 'shop_traveler_steps', ['operator__qa_id'], unique=False)
    op.create_foreign_key(None, 'shop_traveler_steps', 'employees', ['operator__qa_id'], ['id'])
    op.create_foreign_key(None, 'shop_traveler_steps', 'employees', ['operator__init_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_traveler_steps', type_='foreignkey')
    op.drop_constraint(None, 'shop_traveler_steps', type_='foreignkey')
    op.drop_index(op.f('ix_shop_traveler_steps_operator__qa_id'), table_name='shop_traveler_steps')
    op.drop_index(op.f('ix_shop_traveler_steps_operator__init_id'), table_name='shop_traveler_steps')
    op.drop_column('shop_traveler_steps', 'operator__qa_id')
    op.drop_column('shop_traveler_steps', 'operator__init_id')
    # ### end Alembic commands ###
