"""add tables

Revision ID: f69c8d04efde
Revises: bdccfca8a7b8
Create Date: 2025-12-28 11:27:26.127826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69c8d04efde'
down_revision: Union[str, Sequence[str], None] = 'bdccfca8a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lot_material_use', sa.Column('qty_uom', sa.String(), nullable=True))
    op.drop_column('lot_material_use', 'uom')
    op.add_column('raw_batches', sa.Column('qty_uom', sa.String(), nullable=True))
    op.add_column('raw_batches', sa.Column('qty_text', sa.String(), nullable=True))
    op.add_column('raw_batches', sa.Column('size_uom', sa.String(), nullable=True))
    op.add_column('raw_batches', sa.Column('size_text', sa.String(), nullable=True))
    op.add_column('raw_batches', sa.Column('length_uom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_batches', 'length_uom')
    op.drop_column('raw_batches', 'size_text')
    op.drop_column('raw_batches', 'size_uom')
    op.drop_column('raw_batches', 'qty_text')
    op.drop_column('raw_batches', 'qty_uom')
    op.add_column('lot_material_use', sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('lot_material_use', 'qty_uom')
    # ### end Alembic commands ###
