"""rename break

Revision ID: f85aaaa89c4d
Revises: e02cf479a16f
Create Date: 2025-09-05 23:43:51.383183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85aaaa89c4d'
down_revision: Union[str, Sequence[str], None] = 'e02cf479a16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('break_type', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_break_entries_end', 'break_entries', ['end_at'], unique=False)
    op.create_index('ix_break_entries_parent', 'break_entries', ['time_entry_id'], unique=False)
    op.create_index('ix_break_entries_start', 'break_entries', ['start_at'], unique=False)
    op.create_index(op.f('ix_break_entries_time_entry_id'), 'break_entries', ['time_entry_id'], unique=False)
    op.drop_index(op.f('ix_time_breaks_end'), table_name='time_breaks')
    op.drop_index(op.f('ix_time_breaks_parent'), table_name='time_breaks')
    op.drop_index(op.f('ix_time_breaks_start'), table_name='time_breaks')
    op.drop_index(op.f('ix_time_breaks_time_entry_id'), table_name='time_breaks')
    op.drop_table('time_breaks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_breaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('break_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name=op.f('time_breaks_time_entry_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_breaks_pkey'))
    )
    op.create_index(op.f('ix_time_breaks_time_entry_id'), 'time_breaks', ['time_entry_id'], unique=False)
    op.create_index(op.f('ix_time_breaks_start'), 'time_breaks', ['start_at'], unique=False)
    op.create_index(op.f('ix_time_breaks_parent'), 'time_breaks', ['time_entry_id'], unique=False)
    op.create_index(op.f('ix_time_breaks_end'), 'time_breaks', ['end_at'], unique=False)
    op.drop_index(op.f('ix_break_entries_time_entry_id'), table_name='break_entries')
    op.drop_index('ix_break_entries_start', table_name='break_entries')
    op.drop_index('ix_break_entries_parent', table_name='break_entries')
    op.drop_index('ix_break_entries_end', table_name='break_entries')
    op.drop_table('break_entries')
    # ### end Alembic commands ###
