"""add lot_po_duedate

Revision ID: f97e99d3e9c0
Revises: ce4b08dc7abd
Create Date: 2025-12-14 19:38:53.095226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97e99d3e9c0'
down_revision: Union[str, Sequence[str], None] = 'ce4b08dc7abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_lots', sa.Column('lot_po_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_production_lots_lot_po_date'), 'production_lots', ['lot_po_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_lots_lot_po_date'), table_name='production_lots')
    op.drop_column('production_lots', 'lot_po_date')
    # ### end Alembic commands ###
