"""add machines table and machine_id to steps

Revision ID: fbcb1ec076cd
Revises: 1ddb9fc8858c
Create Date: 2025-08-13 22:07:06.800327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcb1ec076cd'
down_revision: Union[str, Sequence[str], None] = '1ddb9fc8858c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_traveler_steps', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.create_index('ix_traveler_steps_machine', 'shop_traveler_steps', ['machine_id'], unique=False)
    op.create_foreign_key(None, 'shop_traveler_steps', 'machines', ['machine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_traveler_steps', type_='foreignkey')
    op.drop_index('ix_traveler_steps_machine', table_name='shop_traveler_steps')
    op.drop_column('shop_traveler_steps', 'machine_id')
    # ### end Alembic commands ###
