"""add redidual in

Revision ID: fcb32b3218b9
Revises: 6fe0bbfe77a0
Create Date: 2025-10-15 13:53:30.702155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb32b3218b9'
down_revision: Union[str, Sequence[str], None] = '6fe0bbfe77a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_invoices', sa.Column('residual_inv', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_invoices', 'residual_inv')
    # ### end Alembic commands ###
