"""init supplier tables

Revision ID: fe36161a025e
Revises: 406dc538b4f3
Create Date: 2025-10-05 21:51:01.521072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe36161a025e'
down_revision: Union[str, Sequence[str], None] = '406dc538b4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_mat_category_catalog',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['supplier_mat_category_catalog.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('supplier_service_catalog',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('supplier_material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('price_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['supplier_mat_category_catalog.code'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'category_code', name='uq_supplier_matcat_once')
    )
    op.create_index('ix_supplier_matcat_lookup', 'supplier_material_categories', ['category_code', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_material_categories_category_code'), 'supplier_material_categories', ['category_code'], unique=False)
    op.create_index(op.f('ix_supplier_material_categories_supplier_id'), 'supplier_material_categories', ['supplier_id'], unique=False)
    op.create_table('supplier_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['service_code'], ['supplier_service_catalog.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'service_code', name='uq_supplier_service_once')
    )
    op.create_index('ix_supplier_services_lookup', 'supplier_services', ['service_code', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_services_service_code'), 'supplier_services', ['service_code'], unique=False)
    op.create_index(op.f('ix_supplier_services_supplier_id'), 'supplier_services', ['supplier_id'], unique=False)
    op.add_column('raw_materials', sa.Column('family_code', sa.String(), nullable=True))
    op.add_column('raw_materials', sa.Column('form_code', sa.String(), nullable=True))
    op.add_column('raw_materials', sa.Column('grade_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_raw_materials_family_code'), 'raw_materials', ['family_code'], unique=False)
    op.create_index(op.f('ix_raw_materials_form_code'), 'raw_materials', ['form_code'], unique=False)
    op.create_index(op.f('ix_raw_materials_grade_code'), 'raw_materials', ['grade_code'], unique=False)
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['grade_code'], ['code'])
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['form_code'], ['code'])
    op.create_foreign_key(None, 'raw_materials', 'supplier_mat_category_catalog', ['family_code'], ['code'])
    op.add_column('suppliers', sa.Column('is_material_supplier', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('suppliers', sa.Column('is_subcontractor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_suppliers_roles', 'suppliers', ['is_material_supplier', 'is_subcontractor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suppliers_roles', table_name='suppliers')
    op.drop_column('suppliers', 'is_subcontractor')
    op.drop_column('suppliers', 'is_material_supplier')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_constraint(None, 'raw_materials', type_='foreignkey')
    op.drop_index(op.f('ix_raw_materials_grade_code'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_form_code'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_family_code'), table_name='raw_materials')
    op.drop_column('raw_materials', 'grade_code')
    op.drop_column('raw_materials', 'form_code')
    op.drop_column('raw_materials', 'family_code')
    op.drop_index(op.f('ix_supplier_services_supplier_id'), table_name='supplier_services')
    op.drop_index(op.f('ix_supplier_services_service_code'), table_name='supplier_services')
    op.drop_index('ix_supplier_services_lookup', table_name='supplier_services')
    op.drop_table('supplier_services')
    op.drop_index(op.f('ix_supplier_material_categories_supplier_id'), table_name='supplier_material_categories')
    op.drop_index(op.f('ix_supplier_material_categories_category_code'), table_name='supplier_material_categories')
    op.drop_index('ix_supplier_matcat_lookup', table_name='supplier_material_categories')
    op.drop_table('supplier_material_categories')
    op.drop_table('supplier_service_catalog')
    op.drop_table('supplier_mat_category_catalog')
    # ### end Alembic commands ###
